package.json

This PR fixes installation issue for `postinstall` script.
FIX: #10

fix: postinstall link command

---

package.json

This is a fix for linking packages inside package to node_modules.
I succeed to run the project and it is so attractive :100:

fix: soft link packages to modules

---

.gitignore
package-lock.json
package.json

Add precommit and prepush scripts

---

.gitignore
README.md
package-lock.json
package.json

- So `docsify-cli` is added when running `npm install`
- Added `docsify-cli` to the `devDependencies`
- Added a script in `package.json` to be able to run the docs locally
- Updated the `README.md` with instructions on running the docs
- Added `.DS_Store` to `.gitignore`

Add docsify to package.json

---

docs/api/Game.md
docs/react/example-2.html
docs/tutorial.md
examples/tic-tac-toe/app.test.js
examples/tic-tac-toe/tic-tac-toe.js
src/both/game.js
src/both/reducer.js
src/both/reducer.test.js

This will be needed for implementing miniMax later per issue #7 , given that we need a standard way to know if the game is finished or not, and who won.

Makes winner evaluation to be part of the Game API instead of being assumed to be in the state.

---

examples/app.js
examples/app.test.js
examples/index.html
examples/routes.js
examples/server.js
examples/singleplayer/index.js
examples/spectator/index.js
examples/tic-tac-toe/board.js
examples/tic-tac-toe/game.js
src/client/client.js
src/server/index.js
src/server/index.test.js

See commit comments for more details, but I basically did the following:
- 'null' playerID on multiplayer is now treated as 'view-only' by the server
- 'null' playerID on singleplayer is now treated as 'hotseat'
- Refactored some code on the example to make it more maintainable

Modify 'null' playerID functionality and refactor Tic-Tac-Toe example

---

src/client/lib/grid.js
src/client/lib/grid.test.js
src/client/lib/token.js
src/client/lib/token.test.js

As discussed in #48 and #53 
Creates a `<Token>` that supports animation when changing x and y. It also receives a hidden function from `Grid` that gets the underlying svg coordinates.

Adding token and grid

---

src/ui/token.js
src/ui/token.test.js

Deboucing Token props change, fixing #84

---

docs/phases.md

Propose fix a typo

---

src/core/random.js
src/core/random.test.js

This PR implements throwing multiple dice; see #68

allow to throw multiple dice

---

docs/multiplayer.md

Correct import typo in multiplayer docs

---

src/ui/grid.js
src/ui/grid.test.js
src/ui/hex.js
src/ui/hex.test.js
src/ui/token.js
src/ui/token.test.js
storybook/hex.js

UI: add mouse hover action props to grid, hex, and token

---

src/client/client.test.js
src/core/flow.js
src/core/flow.test.js

This PR allows to modify `actionPlayers` as per #154, by adding a `changeActionPlayer` event.

allow to modify actionPlayers via Events

---

docs/api/Game.md

Fix style in docs about game

---

src/client/react.js

* [x ] Use a separate branch in your local repo (not `master`).
* [ x] Test coverage is 100% (or you have a story for why it's ok).

replace deprecated function

---

packages/core.js
src/ai/ai.js
src/ai/ai.test.js
src/client/client.js
src/client/client.test.js
src/client/debug/debug.test.js
src/client/log/log.test.js
src/client/multiplayer/multiplayer.test.js
src/core/events.test.js
src/core/flow.test.js
src/core/game.test.js
src/core/random.test.js
src/core/reducer.js
src/core/reducer.test.js
src/core/turn-order.test.js
src/server/api.js
src/server/index.js

this is required in order to develop clients/server/utilities/tests outside of the core repo

export createGameReducer

---

src/core/flow.js

Add config update on phase change

---

src/server/api.js
src/server/api.test.js

for #214 
currently just returning list of given game names, maybe it should have more info?

initial game list api endpoint implementation

---

examples/react/modules/tic-tac-toe/components/authenticated.js

Authentication example was using old URL for join game. I replaced it with the new one.

Tic-Tac-Toe Authentication Example Route Fix

---

examples/react/modules/tic-tac-toe/components/board.js

simplify 'if' expression

---

docs/api/Random.md

Remove duplicate D6 under Wrappers section

---

packages/react.js

Exporting Debug element so it can be re-used

expose Debug element

---

src/server/api.js

API: check secret _before_ handling the request

---

docs/tutorial.md

Just finished the tutorial. This looks very promising. 😀
Anyway, the `AI` module in the tutorial's code is imported from the wrong module. This PR fixes that.

fix tutorial code for AI

---

src/client/client.js

Nicolo will be away for 2-3 weeks starting July 16th 2018, so expect some delays in getting a response.

DRYing createDispatchers

---

docs/multiplayer.md
src/client/multiplayer/multiplayer.js
src/client/multiplayer/multiplayer.test.js

Added ability to specify server protocol

---

package-lock.json
package.json
src/server/index.js
src/server/index.test.js

Fixing #248 
Changing unmaintained dependency koa-socket to koa-socket2. All tests pass and manually tested multiplayer games and it works. (no api change)

Fixing #248

---

src/client/client.test.js
src/client/log/log.js
src/client/log/log.test.js
src/core/flow.js
src/core/flow.test.js
src/core/reducer.js
src/core/reducer.test.js
src/master/master.test.js

This PR is intended to implement #227 part 2. Currently, the action inside a log event is wrapped in an object.
Next steps:

WIP: Custom log messages

---

src/ui/hex-utils.js
src/ui/hex-utils.test.js
storybook/hex.js

A utility function which returns all reachable points given a start, a movement distance, and a set of blocked points

Get reachable hexagonal points within a distance

---

src/server/db/mongo.js

added the useNewUrlParser option to the Mongo connect()

---

docs/random.md

No reason to assume the player is a guy :)

DOCS: Remove gender specific pronoun

---

src/client/client.js
src/client/client.test.js

Adds a field with server sync status to client

Add a server sync status field

---

docs/turn-order.md
src/core/turn-order.js
src/core/turn-order.test.js

Same as #318 but from a non master branch

Turn order active player changes

---

src/server/api.js
src/server/api.test.js

server: fix name of property 'credentials' in server API 'leave'

---

src/core/flow.js
src/core/flow.test.js

Resolves #323 for:
`onTurnBegin`
`onTurnEnd`
`onMove`
`onPhaseBegin`
`onPhaseEnd`

Add Immer to other events

---

src/ui/2d/token.test.js

Improving test coverage for drag and drop

---

src/lobby/connection.js

Allow https urls to be passed to lobby

---

examples/react-web/src/lobby/lobby.js
src/lobby/react.js

Fixes:
- broken single player mode in component Lobby
- incomplete URL's in Lobby example

Fix lobby example

---

docs/turn-order.md

Document playOrder for custom turn orders

---

src/server/db/firebase.js
src/server/db/firebase.test.js

Changes default Firebase return value to undefined

---

examples/react-web/src/chess/board.js

Fixes #370 
* [ x ] Use a separate branch in your local repo (not `master`).
* [ x ] Test coverage is 100% (or you have a story for why it's ok).

Fixing chess reload

---

src/client/react-native.js
src/client/react.js

In order to do a single player mode, I need a way to make the bot play the next move. Exposing the step on the board props allows me to call it as soon as the user finishes a move.
* [ x ] Use a separate branch in your local repo (not `master`).
* [ x ] Test coverage is 100% (or you have a story for why it's ok).

Adding step props to the Board

---

src/lobby/create-room-form.js
src/lobby/react.test.js

Handle correctly a minimum number of players bigger than 2

lobby: fix issue #390 (minimum number of players bigger than 2)

---

examples/react-web/src/chess/multiplayer.js
examples/react-web/src/lobby/lobby.js
examples/react-web/src/tic-tac-toe/authenticated.js
examples/react-web/src/tic-tac-toe/spectator.js

Fixes some examples if you are running from other machine not localhost

---

docs/README.md
docs/made_with.md

The criteria I used was: 
- I looked into any [dependent projects](https://github.com/nicolodavis/boardgame.io/network/dependents) that had two or more stars.
- I included any that had a link to a working demo
- Exceptions:  "Bad Flamingo" with good screenshots and large star count and "Four in a row" which has a very detailed tutorial.
The sorting of these projects is by number of Github stars.

Creating list of projects made with boardgame.io

---

docs/README.md
docs/_sidebar.md
docs/notable_projects.md

Rename ```made_with.md``` to ```notable_projects.md```~, add to sidebar~

Rename made_with.md to notable_projects.md

---

docs/api/Client.md

Adds example on how to specify server protocol in Client.md

Document specifying server protocol

---

docs/api/API.md
src/server/api.js
src/server/api.test.js

Get specific instance of a room by its ID

Get specific instance of a room by its ID

---

docs/api/Lobby.md
src/server/api.js
src/server/api.test.js

More refactoring for lobby

---

src/server/api.js
src/server/api.test.js

Check if required parameters are passed to API

---

docs/api/Lobby.md
src/lobby/connection.js
src/server/api.js
src/server/api.test.js

Rename playerCredentials to credentials for /leave endpoint per @nicolodavis https://github.com/nicolodavis/boardgame.io/pull/414#discussion_r289669536.
Update src/lobby/connection.js accordingly.

Rename playerCredentials to credentials for /leave endpoint

---

src/server/api.js

Fixes joining/leaving a room for playerID = 0.
Closes #420

fix: Fix join/leave a room when playerID is 0

---

docs/documentation/api/Client.md
src/client/client.js
src/client/client.test.js
src/client/react-native.js
src/client/react.js
src/client/transport/local.js
src/client/transport/socketio.js
src/master/master.js
src/master/master.test.js

Surface game metadata and player nicknames in client / react props

---

docs/documentation/notable_projects.md

Adding Elevation of Privilege to the list, maintaining alphabetical order.

Updating notable projects

---

docs/documentation/api/Client.md

Fix formatting on API docs Client.md

---

docs/documentation/turn-order.md

Restores changes made to the turn order API docs in #453 and #454, which I just noticed are no longer on the `docs` branch.
Preview of the changes: https://delucis-restore-turn-order-docs--delucis-bgio-docs.netlify.com/documentation/#/turn-order

docs: Update turn-order.md

---

src/client/transport/socketio.js

Call gameMetadataCallback() before dispatching to fix #467

Call gameMetadataCallback() before dispatching to fix #467

---

CONTRIBUTING.md
docs/documentation/api/Client.md
docs/documentation/api/Game.md
docs/documentation/api/Server.md
docs/documentation/concepts.md
docs/documentation/secret-state.md

I read through the new docs and here are a handful of tiny proposed changes.

docs: Minor tweaks and updates

---

src/core/turn-order.js

feat: Apply `value` argument last in `setActivePlayers`

---

examples/react-web/src/chess/multiplayer.js
examples/react-web/src/redacted-move/multiview.js
examples/react-web/src/secret-state/multiview.js
examples/react-web/src/simulator/simulator.js
examples/react-web/src/tic-tac-toe/authenticated.js
examples/react-web/src/tic-tac-toe/multiplayer.js
examples/react-web/src/tic-tac-toe/spectator.js
examples/react-web/src/undo/index.js
integration/src/App.js
package.json
packages/main.js
packages/multiplayer.js
src/client/client.js
src/client/client.test.js
src/client/react-native.js
src/client/react-native.test.js
src/client/react.js
src/client/react.test.js
src/client/transport/local.js
src/client/transport/local.test.js
src/client/transport/socketio.js
src/client/transport/socketio.test.js
src/client/transport/transport.js
src/core/reducer.js
src/core/reducer.test.js
src/lobby/react.js
src/lobby/react.test.js
subpackages.js

clientImpl now expects {multiplayer: falsy or transportFactory}
react client's usage is not affected
closes https://github.com/nicolodavis/boardgame.io/issues/418

refactor transport out of clientImpl

---

src/client/react.js

override debug from client

---

docs/documentation/events.md

docs: Tweak events documentation

---

src/lobby/react.js
src/lobby/react.test.js
src/lobby/room-instance.js

A few improvements to lobby as listed in #354:
- auto refresh of rooms state
- add button 'leave' to rooms that are full and ready to play

lobby auto refresh + leave game ready to play

---

scripts/clean.js
scripts/proxy-dirs.js

* nearwood/issue-518
* devops scripts to fix an export

Add server to proxy-dirs and clean scripts to fix #518

---

docs/documentation/notable_projects.md

Change notable_projects.md to reflect updated (plural) domain for FreeBoardGames.org

Change notable_projects.md to reflect updated (plural) domain for FreeBoardGames.org

---

docs/documentation/api/Lobby.md
src/server/api.test.js
src/server/api.ts

Improve Lobby API: room instances

---

docs/documentation/plugins.md

Hi 👋 
It looks like the plugin documentation is not up-to-date with the changes introduced in 4a468aba5258. This PR updates the documentation based on the code in https://github.com/pardahlman/boardgame.io/blob/master/src/plugins/main.js

Update plugin documentation

---

src/client/react-native.test.js
src/client/react.test.js
src/client/transport/local.js
src/client/transport/local.test.js
src/client/transport/socketio.js
src/client/transport/socketio.test.js
src/client/transport/transport.js

Remove namespacing in gameIDs on client side

---

src/plugins/plugin-player.ts
src/types.ts

Please see issue #611 
Re: Test coverage. Were you guys looking for type tests on these? Didn't see any other ones.

Typescript enhancements

---

docs/documentation/multiplayer.md

This PR links the documentation on optimistic updates in `multiplayer.md` with the instructions for disabling optimistic updates in `secret-state.md`.

Document disabling optimistic updates

---

docs/documentation/deployment.md
docs/documentation/sidebar.md

* [o] Use a separate branch in your local repo (not `master`).
* [o] Test coverage is 100% (or you have a story for why it's ok).

Add deployment to Heroku in documentation

---

docs/documentation/deployment.md
docs/documentation/sidebar.md

Added backend only doc in deployment

---

src/client/react.js

expose log as a prop in the React client

---

docs/documentation/api/Lobby.md
src/master/master.ts
src/server/api.test.ts
src/server/api.ts
src/types.ts

Ok, so my coverage isn't 100%, I'm not too familiar with unit testing (I know, not cool), I did the API part but there's this one line that isn't covered (api.test.js:342)

Add an endpoint to the Lobby  to add additional information  to a player

---

docs/documentation/notable_projects.md

I created a cool little open source board game that might be a nice addition to notable projects. I used React + Boardgame.io

Add mosaic to notable_projects.md

---

src/master/master.test.ts
src/master/master.ts
src/types.ts

feat(master): Update metadata with gameover value on game end

---

docs/documentation/storage.md

Resubmitting as per discussion in https://github.com/nicolodavis/boardgame.io/pull/648

docs: Add link to Azure Storage database connector

---

docs/documentation/api/Lobby.md

Add playAgain endpoint to Lobby documentation

---

README.md

This also adds a few other small improvements to the README file.
Fixes #660.

(doc) Add a more visible link to gitter community in README.

---

docs/documentation/api/Game.md
docs/documentation/deployment.md

1. Added `minPlayers` and `maxPlayers` as optional fields in `Game.md`
2. Corrected small typo in `deployment.md`

fix(docs): Add minPlayers and maxPlayers to Game.md

---

packages/internal.ts

Add `Sync` export
Its just export added, no test needed.

Add Sync export 

---

docs/documentation/notable_projects.md

I created a multiplayer buzzer system for trivia night or online quiz bowl using React and Boardgame.io!

Add multibuzzer to notable_projects.md

---

docs/documentation/notable_projects.md

I developed a clone of the 2 player card game Jaipur using Boardgame.io and React as a little personal project and it would be great to see it added to this list.

docs: Add Udaipur to notable_projects.md

---

src/client/debug/main/Controls.svelte

Solves #715
Consider approach, is there a reason not to commit all state to localStorage?

Save all state to localStorage, not just G and ctx

---

scripts/changelog.js

One of the "good first issue" issues. Fixes #721.
I've tried to follow the commit message format I see in some of the commit messages - perhaps some documentation in CONTRIBUTION.MD specifying your preferred format would be helpful?

fix(docs): update changelog script to add bullet points (#721)

---

examples/react-web/package.json
examples/react-web/src/chess/grid.js

Fixes examples:
- Fixes #720
- Fixes grid on chess that wasnt rendering properly

Fix examples

---

examples/react-web/src/chess/index.js
examples/react-web/src/chess/multiplayer.js

This is to allows us to run this example in separate devices. Especially useful to debug connectivity issues like #713

Splits chess multiplayer into player 0, 1 and spectator

---

src/client/transport/socketio.ts

Fixes #713

---

src/client/transport/local.ts

Local(): Typescript error: "An argument for 'opts' was not provided."

---

docs/documentation/CHANGELOG.md

Fixed consistency for bullet points in the list

---

docs/documentation/CHANGELOG.md

relocate feat and fix to their correct categories

---

docs/documentation/storage.md

add Postgres Storage Adapter to storage docs

---

docs/documentation/api/Game.md
docs/documentation/undo.md
src/core/flow.test.js
src/core/flow.ts
src/core/game.test.js
src/core/game.ts
src/core/reducer.test.ts
src/core/reducer.ts
src/types.ts

#738 
Please go through the changes and let us know if there are any more changes required.

feat(game) disable undo feature by using disableUndo flag

---

docs/documentation/concepts.md

docs: Document requirement that G must be JSON-serializable

---

.github/workflows/test.yml

add integration test to GitHub action

---

docs/documentation/notable_projects.md

Add splendor game to notable projects.

---

docs/documentation/tutorial.md

docs(Tutorial): Fix Parcel compatibility issue

---

docs/documentation/notable_projects.md

docs(notable projects)Add Camelot repository

---

src/client/debug/Debug.svelte
src/client/debug/Menu.svelte
src/client/debug/ai/AI.svelte
src/client/debug/ai/Options.svelte
src/client/debug/log/LogEvent.svelte
src/client/debug/main/Controls.svelte
src/client/debug/main/Hotkey.svelte
src/client/debug/main/Main.svelte
src/client/debug/main/PlayerInfo.svelte

- Make debug tab menu, Hotkey component, and log entries keyboard accessible.
- Fix colour contrast in a few places.
- Improve HTML semantics.

fix(debug): Improve debug panel accessibility

---

docs/documentation/notable_projects.md

Add a good project built on boardgame.io
* [√ ] Use a separate branch in your local repo (not `master`).
* [ √] Test coverage is 100% (or you have a story for why it's ok).

Update notable_projects.md, add a project

---

docs/documentation/notable_projects.md
docs/documentation/theme.css

Sort and uniformize the list of projects using boardgame.io
* Sort games in alphabetical order
* Make each list item uniform
* Make the first paragraph marginally more concise
* Add github stars to open source projects, to highlight popular
projects
* Reorganize the markdown code
Result:

Sort and uniformize the notable games

---

docs/documentation/notable_projects.md

docs: Add Coup to notable_projects.md

---

docs/documentation/notable_projects.md

docs: Add Tien Len to Notable Projects

---

examples/react-web/src/chess/board.js
examples/react-web/src/chess/chat.js
src/client/client.test.ts
src/client/client.ts
src/client/react-native.js
src/client/react.tsx
src/client/transport/local.test.ts
src/client/transport/local.ts
src/client/transport/socketio.test.ts
src/client/transport/socketio.ts
src/client/transport/transport.ts
src/master/master.test.ts
src/master/master.ts
src/server/transport/socketio.test.ts
src/server/transport/socketio.ts
src/types.ts

So I read issue #460 about out of the box chat support and this is WIP for a very basic, non-persistent, chat messages passed between socket-io clients. If you guys think this is a good idea I will polish it and add tests etc. For now I just did something to see if my theory would work in practice. I tested it using the chess example and added some basic UI for it.
@delucis @nicolodavis

Chat messages

---

examples/react-web/package.json
package-lock.json
package.json

- Remove `uuid`, `lru-cache`, `style-loader` and `ajv`.
- Move `react-router-dom` to examples package.

chore(deps): Remove unused dependencies

---

docs/documentation/notable_projects.md

docs: Add LHoG to Notable Projects

---

.gitattributes
docs/documentation/api/Game.md
package-lock.json
package.json
src/client/client.test.ts
src/client/client.ts
src/client/transport/socketio.test.ts
src/client/transport/socketio.ts
src/core/action-creators.ts
src/core/action-types.ts
src/core/game.ts
src/core/reducer.test.ts
src/core/reducer.ts
src/master/master.test.ts
src/master/master.ts
src/server/transport/socketio.test.ts
src/server/transport/socketio.ts
src/types.ts

Implement feature request from issue https://github.com/boardgameio/boardgame.io/issues/757

Add an option to use delta state for transport

---

src/types.ts

Type exports

---

docs/documentation/notable_projects.md

docs(notable_projects): Add Forbidden Desert

---

package-lock.json
package.json

chore(deps): Make @types/koa-router a direct dependency

---

docs/documentation/api/Client.md
docs/documentation/api/Game.md
docs/documentation/sidebar.md
docs/documentation/typescript.md

docs: Document usage with Typescript

---

docs/documentation/api/Lobby.md
src/lobby/client.test.ts
src/lobby/client.ts
src/server/api.test.ts
src/server/api.ts
src/server/util.ts
src/types.ts

- [✅] Use a separate branch in your local repo (not `main`).
- [✅ ] Test coverage is 100% (or you have a story for why it's ok).
Solves #1012

feat(lobby): use first available `playerID` when joining a match

---

README.md

Adds a README banner as suggested in https://github.com/vshymanskyy/StandWithUkraine.
Any opposition to this @nicolodavis @vdfdev?

docs(README): Add Stand With Ukraine banner

---

docs/documentation/random.md

docs: fix typo in random.md

---

docs/documentation/notable_projects.md

docs: Update notable_projects.md

---

docs/documentation/notable_projects.md

Update the URL for Lewis's House of Games

Update URL for LHOG

---

docs/documentation/notable_projects.md

docs: Update santorini url

---

src/core/reducer.test.ts
src/core/reducer.ts
src/master/filter-player-view.test.ts
src/types.ts

Implemented as requested in #1059

feat: Conditional log redacting in long form move

---

docs/documentation/notable_projects.md

Hey,
I made a project called "Chessweeper" with boardgame.io that is a mix between Chess and Minesweeper \
The game is playable here: https://chessweeper.zirk.eu

Add new project to notable_projects.md

---

docs/documentation/notable_projects.md

You can check it out here: https://2048-online.io/.
- [x ] Use a separate branch in your local repo (not `main`).
- [ x] Test coverage is 100% (or you have a story for why it's ok).

Added 2048 build using boardgame.io

---

docs/documentation/notable_projects.md

Add a new game to projects

---

README.md

Remove unmaintained repo banner
