.babelrc, package.json
Now babel uses current version of node env for transpiling.
=> Fix test for multi node env

docs/tutorial.md
The tutorial is great, but it was missing a bit crucial step for installing the actual `boardgame.io` framework. This PR simply adds the `npm install` step to the pre-setup 😸
=> Add boardgame.io install step to Tutorial.md

docs/react/example-2.html, docs/tutorial.md, examples/tic-tac-toe/tic-tac-toe.js
Issue https://github.com/google/boardgame.io/issues/9
In example 2, you can skip a player's turn by clicking on an already filled cell.
- I'm assuming that the code in `example-2.html` in the script tag is what is running the game in the example docs and not `tic-tac-toe.js`
- In the code in the script tag it's not checking if the cell `id` is null or not, it's currently checking only if there is already a winner
- Updated to check if the current cell is not `null`
- I also updated `!=` to `!==` in `tic-tac-toe.js` to be consistent with the next line
**Note**: I've never used docsify (which I think is what's powering the docs page?) before and I was tinkering around trying to get the docs page to run locally but I was unsuccessful, so I didn't manage to test this fix for myself. However, …
=> Fix the example 2 double click bug, use !== instead of !=

AUTHORS, docs/api/Client.md, docs/api/Game.md, docs/api/Server.md, docs/phases.md
Updates a few of the documentation pages.
* In `Game` has two examples of usage. Merges them into one.
* In `Game`, switch the import from `game` to `core`.
* In `Server`, use an `import` instead of a `require`.
* Removes a link to localhost
* Red PR
=> update documentations for imports

docs/CHANGELOG.md
the changelog is not correctly formated for the new versions, also found a small typo (should be 0.17.1) and made all the commits clickable...
=> fix formatting of changelog

examples/modules/liars-dice/components/multiview.js
The description in the example for player 2 should be 
```
<App playerID="2"/>
```
Instead of 
```
<App playerID="1"/>
```
=> Fix a typo in example

.babelrc, package-lock.json, package.json
The tests on my machine have always failed when I tried to push
```
server              |        0 |        0 |        0 |        0 |                |
db.js              |        0 |        0 |        0 |        0 |... 26,36,44,45 |
index.js           |        0 |        0 |        0 |        0 |... 130,132,133 |
```
With an error that was pointing at this
```
*/test('basic', async function () {var db
^^^^^
```
On https://facebook.github.io/jest/docs/en/tutorial-async.html, it says to add the `env` preset to use async/await in tests. Adding it fixed this for me. It should be innocuous for others where this test already ran fine.
=> preset-env

src/client/debug/debug.css, src/client/debug/debug.js, src/client/debug/debug.test.js
Hey,
the behaviour of the debug UI is pretty confusing.
Calling a move/event function with `[1, 2, 3]` results in a call with arguments `undefined, 2, undefined`.
This changes the arguments to all be evaluated in one call, thus `argText.split(',')` is no longer needed. As a result the test `3, unknown, 4` will error instead of evaluating to `3, undefined, 4`. I'd say this behaviour is sensible. I've changed the test accordingly.
This also implements basic error reporting.
=> Debug UI: fixes related to errors in arguments

src/client/log/log.js
I think the debug log pane is busted for games with multiple phases. You can demo this if you look up the phases game in examples http://localhost:8000/#/phases and turn on the log window. This quick fix sort of gets it operational, but it still gets messed up if you mouseover past history. I'm kind of drunk sorry ballmer peak doesn't help with sentence structure.
=> fix display of log with phased game

src/core/reducer.js, src/core/reducer.test.js
Fixes #133 
@nicolodavis Please check whether `initial` is correctly initialized. `initial.ctx.random` now contains `PRNGState.get()` after `setup` has been evaluated. The true initial state would be not running anything (no `setup` either), and then having one state that evaluates `setup`.
=> Fix random setup

package-lock.json, package.json, src/client/debug/debug.js, src/client/react.js, src/client/react.ssr.test.js
Fixes #22 !!!
- Creates test for making sure we are not throwing errors when doing SSR. (Cool stuff that jest can emulate node!)
- Replaces react-json-view with simple \<pre\> and JSON (react-json-view throws "window is not defined")
- Avoid establishing socket.io connection to the server if you are, er, executing on the server.
=> Enabling server-side-rendering for boardgame.io (fixes #22)

src/client/multiplayer/multiplayer.test.js, src/core/flow.js, src/core/flow.test.js
This PR changes `FlowWithPhases` `processMove` by also running the _endPhase_ event when the game ends. I've run across this while reading the code.
The intention is to streamline the flow of events. Currently, when the game ends, only the _endTurn_ event is fired. However, I see no reason not to run the _endPhase_ event also.
Also, since I was on it, I've added some assertions to bring coverage to full 100%. If that was really necessary or not, I don't know. 
* [ x] Use a separate branch in your local repo (not `master`).
* [ x] Test coverage is 100% (or you have a story for why it's ok).
=> Run endPhase event (analogue to endTurn) when game ends

docs/_sidebar.md, docs/api/Client.md, docs/debugging.md, src/client/client.js, src/client/client.test.js, src/client/multiplayer/multiplayer.js, src/client/multiplayer/multiplayer.test.js, src/client/react.js
Adds an optional param to a Client which allows the user to hook into the Redux store with an enhancer or middleware.
The main motivation for this is to hook into it with [`redux-logger`](https://github.com/evgenyrodionov/redux-logger) or [Redux Devtools](http://extension.remotedev.io/), and is documented in an additional page.
=> allow optional redux enhancer

src/core/flow.js, src/core/flow.test.js
When a move is made it checks if the turn should end and if the phase should end.
In the situation of `phase A` ending the turn and the phase, it should start `phase B` end check `phase B` `endPhaseIf`.
Expected:
`phase A` - call onPhaseEnd 1 time
`phase b` - don't call onPhaseEnd
=> Fix bug that was ending phase incorrectly

src/client/react-native.js, src/client/react-native.test.js
The existing implementation doesn't support enhancers for react-native. This prevents redux debugging from working for RN clients.
Fixes #185
=> Allow enhancers for react-native clients

docs/phases.md
Hi, I'm doing tutorials and perhaps found a typo in phase documentation (`flow.phase` => `flow.phases` ) . Thanks!
=> Fix typo in docs about phase

src/server/api.js, src/server/api.test.js
If an environment variable `LOBBY_SECRET` is provided when the API server is started, then all API requests will require that secret in a header named `lobby-secret`. (Issue #198)
This check is provided as a middleware for the API koa server.
=> Allow the lobby API to require a secret for all requests

src/server/api.test.js
I didn't feel like the test for games list was particularly useful as it didn't actually test what we're interested in testing. Now the test checks to ensure that the returned list contains the names of available games.
=> Updated games list test to be more useful

docs/roadmap.md, src/client/client.js, src/client/client.test.js, src/client/debug/debug.js, src/client/debug/debug.test.js, src/client/log/log.test.js, src/client/multiplayer/multiplayer.js, src/client/multiplayer/multiplayer.test.js, src/core/action-creators.js, src/core/action-types.js, src/core/events.js, src/core/flow.js, src/core/flow.test.js, src/core/reducer.js, src/core/reducer.test.js, src/server/index.js, src/server/index.test.js
This PR implements part 3 of #227 (deltalog).
The server's reaction to an `action` command is changed and only added log entries are transferred (the `deltalog`). At client side, the deltalog is added to the current state`s log again.
`_initial` is stripped from `action` commands since it's only necessary to transfer it once during the initial `sync` to the server. It also gets added at client side.
=> Compactify transferdata (deltalog, _initial)

package-lock.json, package.json
=> use patch-1 of graceful-fs to avoid jest cache errors

examples/react/modules/turnorder/components/board.js, examples/react/modules/turnorder/game.js, src/core/flow.js, src/core/flow.test.js, src/core/turn-order.js, src/core/turn-order.test.js
This PR fixes the militia example (see #154, part 5).
There are now two moves (_playMilitia_ and _dropCards_). For dropping cards to work for players that are action players but not the current player, I had to allow calling events for those players, because otherwise they would not be allowed to change action players.
=> add allOthers option to setActionPlayers

examples/react/modules/tic-tac-toe/game.js, src/client/log/log.css, src/client/log/log.js, src/client/log/log.test.js, src/core/flow.js, src/core/reducer.js, src/core/reducer.test.js
This PR is part of #227. It allows to actually set a log payload from a move and have it visualized. I've modified the `clickCell` method on the Tic-Tac-Toe example to set a payload.
@nicolodavis Please have a look at the visualization - I played around with the CSS (`overflow` and the fixed height) to no avail; perhaps you have a suggestion on how to visualize a payload.
=> Allow to set payload onto a log event

src/server/api.js, src/server/api.test.js, src/server/db/firebase.js, src/server/db/firebase.test.js, src/server/db/inmemory.js, src/server/db/inmemory.test.js, src/server/db/mongo.js, src/server/db/mongo.test.js
This PR introduces 2 new API endpoints for the future lobby implementation:
- _list_ allows returning a list of instances for a given game
- _leave_ is the symmetric of _join_ ; note that after the last player leaves a game instance, it is automatically destroyed
=> server: add new API endpoints 'list' and 'leave'

src/server/db/index.js, src/server/db/index.test.js, src/server/db/mongo.js
Fixed warning in MongoDB and switched .insert() to .insertOne()
Added process.env.MONGO_DATABASE to set the default database name for Mongo in DBFromEnv().
=> add MONGO_DATABASE env variable

src/client/client.js, src/client/client.test.js, src/core/flow.js, src/core/reducer.js, src/core/reducer.test.js
This PR shall fix #302. The problem is that the log of the player that played the move is updated twice: Once for the MAKE_MOVE action, and a second time for the UPDATE action. The PR modifies this behaviour to NOT update the log inside UPDATE for the player that played the action.
Please have a special eye onto the update action. I'm pretty unsure whether this should have a payload at all since the action creator does not take it.
=> Prohibit second log event during Update

docs/api/Server.md
doc: remove some colons in code blocks that were not correctly converted to html
=> fix some markdown code blocks of Server API documentation

src/core/flow.js, src/core/flow.test.js
Fixes #339 by using returned G instead of state.G, added test handling.
=> Allow result of onPhaseBegin to influence turn order

src/client/client.js, src/client/client.test.js, src/client/debug/debug.js, src/client/debug/debug.test.js
This makes the step function accept a Promise (or keep accepting normal results too) from the bot.play(). [FreeBoardGame.org](https://FreeBoardGame.org) needs this because we are integrating with Stockfish for chess, which uses a Web Worker, and we need to wait for a callback to get the response with the move.
=> Making step accept a Promise from bot.play()

python/boardgameio.py, python/test_boardgameio.py
- replace unmaintained dependency socketIO_client with socketIO_client_nexus
- handle new message 'update'
=> python bot: fix for #379

src/core/turn-order.js, src/core/turn-order.test.js
- Removes _actionPlayersOthers because it is never read
- Defaults _actionPlayersOnce to false rather than undefined
Fixes nicolodavis/boardgame.io#381
=> Don't leak undefined ctx properties from turnOrder.actionPlayers

docs/CHANGELOG.md, src/core/reducer.js, src/core/reducer.test.js
add tests for undo and redo of actions that change phase.
* [x ] Use a separate branch in your local repo (not `master`).
* [x ] Test coverage is 100% (or you have a story for why it's ok).
=> update _undo to reflect current ctx

docs/secret-state.md
The `player=1` prop didn't work for filtering `players` data in my environment. It worked by fixing it to `playerID`.
c.f. https://github.com/nicolodavis/boardgame.io/blob/fb19e9b9abe5adf5f82b5ca89eb7f66630686138/examples/react-web/src/secret-state/multiview.js#L27
- just doc fix so I haven't check it
=> Fix prop name in secret-state doc

package-lock.json, src/client/transport/socketio.js, src/client/transport/socketio.test.js
Auto-add trailing slash to server only if needed
I spent a ton of time trying to figure out why ```{ server: 'http://bgioserver/' }``` wasn't working -- I didn't realize that BGIO added the trailing slash for me.  Now BGIO will only add the trailing slash if it is necessary.
=> Auto-add trailing slash to server only if needed

docs/api/Lobby.md, src/server/api.js, src/server/api.test.js
Add /rename endpoint for lobby.
=> Add /rename endpoint for lobby

src/client/client.js, src/client/client.test.js
Hi,
I'm implementing a custom transport. Having a parameter that just override transport is not very useful as the transport will need access to things like the store (same way that local and socketio transport do).
* [V] Use a separate branch in your local repo (not `master`).
* [V] Test coverage is 100% (or you have a story for why it's ok).
=> custom client transport should be a constructor (IMO)

docs/index.html
Adds text search plugin to docsify– closes #415.
=> Add search plugin to docs

src/server/api.js, src/server/api.test.js
This endpoint will enable a "play again" button in multiplayer games. It should work like this:
- If a player wants to play again and clicks on the button, a request to this end point will provide a new room id.
- The player then can join this new room id with the same player id it had previously.
- If another player also clicks on the button, the same room id will be provided.
- If all players join, then they can play again.
* [ x ] Use a separate branch in your local repo (not `master`).
* [ x ] Test coverage is 100% (or you have a story for why it's ok).
=> Create play again endpoint

src/master/master.js, src/master/master.test.js
This fixes #410. Unless that issue is way more complex than I thought.
Sorry I been gone for a while. Still want to help a lot with this repo. :smile:
=> No payload is not an authentic player

tsconfig.json
Mimic Node.js module resolution to avoid warnings when using relative imports.
=> TypeScript: Mimic Node.js module resolution

packages/core.js
Because `setStage` has been moved out of `turn.order`, the `TurnOrder` defaults have been split in `src/core/turn-order.js`. This PR exposes the new `Stage` object via the core package to use like the `TurnOrder` object:
```js
import { Stage } from 'boardgame.io/core'
```
```js
turn: {
setStage: Stage.ANY_ONCE
}
```
=> feat: Expose the `Stage` defaults object via core package

examples/react-web/src/turnorder/simulator.js, packages/core.js, src/ai/bot.js, src/client/client.js, src/client/client.test.js, src/core/flow.js, src/core/flow.test.js, src/core/turn-order.js, src/core/turn-order.test.js, src/master/master.js
`ANY_ONCE` and `OTHERS_ONCE` no longer end the phase as before. I needed an `endIf` function to achieve that:
```js
phase: {
turn: {
setStage: Stage.ANY_ONCE
},
endIf: (G, ctx) => ctx.numMoves && ctx.stage === null,
}
```
First, a bug:
Once `stage` is empty, it is set to `null`. For example, with `ANY_ONCE` as moves are made:
```js 
stage: { 0: '', 1: '' } // no moves made
stage: { 0: '' }        // player 1 moved
stage: null             // player 0 moved
```
Because the `once` setting doesn’t end the phase as before, the current player can still make a move (control of moves returns from the stage to the phase/turn). A move triggers `processMove`, but `processMove` currently tries to fetch keys from the `ctx.stage` object when `ctx._stageOnce` is `true`, so when it encounters `null` a …
=> Fix “once” and rename `stage` to `activePlayers`

examples/react-web/src/phases/diagram.js, examples/react-web/src/turnorder/example-all-once.js, examples/react-web/src/turnorder/example-all.js, examples/react-web/src/turnorder/example-custom-from.js, examples/react-web/src/turnorder/example-custom.js, examples/react-web/src/turnorder/example-once.js, examples/react-web/src/turnorder/example-others-once.js, examples/react-web/src/turnorder/example-others.js, examples/react-web/src/turnorder/simulator.css, examples/react-web/src/turnorder/simulator.js
As discussed in #442. Mainly this updates the turn order simulator, but I also fixed the Phases Diagram example.
Some of the turn order implementations are quite different after the overhaul, so you might want to check you’re happy with my interpretation of the originals.
I’ve tweaked the simulator by adding a display for the current stage of each player and made the phase show `null` when the phase is `null` (previously it would have been `'default'` in those cases).
=> Update examples for phases overhaul

src/core/flow.js, src/core/flow.test.js
Currently on phase end, `playOrderPos` is hard reset to `0`:
https://github.com/nicolodavis/boardgame.io/blob/a2961c81ce1393e3d6e789e33347ead180b33983/src/core/flow.js#L562
This could make sense, but it makes it difficult to create a phase which maintains or increments the current position when it starts. If `turn.order.first` tries to use `ctx.playOrderPos` or `ctx.currentPlayer`, they have already been reset.
This PR adds a test asserting `playOrderPos` shouldn’t change and removes the hard reset. It also changes one test that was now failing, but I think shouldn’t have been given the proposed changes.
I understand the simplicity of a new phase starting new play sequence, so maybe that could be maintained as a default, but `first: (G, ctx) => ctx.playOrderPos` should probably also …
=> Maintain currentPlayer/playOrderPos when phase ends

examples/react-web/src/turnorder/example-all-once.js, src/core/flow.js, src/core/flow.test.js, src/core/turn-order.js, src/core/turn-order.test.js
Contributes towards #445
- Move reset behaviour behind a `revert` flag in `setActivePlayers`
- Convert `_prevActivePlayers` to an array, which stores a stack of active player values
- Remove `activePlayersDone` from `ctx`
=> Implement revert, use array for _prevActivePlayers & remove activePlayersDone

src/core/flow.js, src/core/turn-order.js, src/core/turn-order.test.js
Continuing work towards #445
This enables a `next` option for `setActivePlayers`/`turn.activePlayers`, including support for nested `next` options.
=> Enable `next` option for `setActivePlayers`

docs/documentation/turn-order.md
This updates the turn order docs. Main things are:
- renaming `actionPlayers` to `activePlayers`
- `TurnOrder` becoming `turn.order`
- splitting of default configs into `ActivePlayers` and `TurnOrder`
- `moveLimit` and `next` features
I haven’t documented `revert` here, because it’s really relevant to `setActivePlayers`, which is currently undocumented.
=> docs: Update turn-order.md

docs/documentation/turn-order.md
- Remove references to `flow` and `Game` in turn-order.md
- Fix `turn` docs, splitting `turn.order` & `turn.activePlayers`
- Add `moveLimit` and `endIf` to `turn` docs
=> docs: Fix some more changes in Turn Order docs

examples/react-web/src/turnorder/example-others-once.js, src/core/flow.js, src/core/turn-order.js, src/core/turn-order.test.js
=> feat: Support move limits in `setActivePlayers`

src/core/turn-order.js, src/core/turn-order.test.js
Closes #479 
- Player-specific move limits take precedence. For example, the following sets the player’s move limit to 2, not 1:
```js
setActivePlayers({
player: { stage: 'A', moveLimit: 2 },
moveLimit: 1,
})
```
- I wrote a helper `ApplyActivePlayerArgument()`, to simplify setting a player’s stage and move limit given an argument that can be a stage (`string`, `boolean`, `number`, `null`) or an object (shape: `{ stage, moveLimit }`). It sacrifices a little bit of efficiency, because parsing the argument happens for every player (for example for `all` and `others`) instead of once and then applied for all. I think it’s still cleaner to separate this logic out into a single function.
- Setting a move limit with the long-form syntax *requires* an accompanying stage field, so the following …
=> refactor: Change moveLimit syntax in setActivePlayers

docs/documentation/stages.md
[Preview →](https://delucis-docs-advanced-move-limit--delucis-bgio-docs.netlify.com/documentation/#/stages?id=advanced-move-limits)
=> docs: Document long-form move limit syntax for `setActivePlayers`

src/core/flow.js, src/core/flow.test.js
The new docs [describe a `next` option in the config for stages](https://boardgame.io/documentation/#/stages?id=exiting-stages), but this wasn’t actually implemented.
This PR adds a test for that behaviour and fixes it.
=> fix: Move player to “next” stage on `endStage`

docs/documentation/api/Client.md, docs/documentation/tutorial.md
This tries to improve the documentation around AI/bots following @julienroulle’s questions on Gitter. In the process I’ve also tidied up some small things I came across.
I’m not sure if some of this was deliberately undocumented while waiting for #383 — i.e. not explicitly advising how to call `step` from the client — but it  seemed like it might be worth adding for now.
I think [this is the CodeSandbox referenced](https://codesandbox.io/s/boardgameio-5lbe5) on Gitter, but I suspect it was not intended to have auto-stepping AI included in any case.
=> docs: Improve documentation around bots and `step()`

docs/documentation/turn-order.md, src/core/flow.test.js, src/core/turn-order.js, src/core/turn-order.test.js
This would close #517 
1. `TurnOrder.DEFAULT` will now increment the current player at the start of a phase and includes a check to prevent incrementing if the phase is a game’s starting phase.
2. Adds `TurnOrder.CONTINUE` to provide the old default behaviour for those who need it. Is this a good name? I couldn’t think of anything clearer that would still be concise.
This change will break current behaviour for anyone:
- Using v0.33 or higher, AND
- Using phases, AND
- Using `TurnOrder.DEFAULT` directly or not setting a custom `turn.order.first`
If currently using the default turn order directly, use `TurnOrder.CONTINUE` instead:
```diff
import { TurnOrder } from 'boardgame.io/core'
const turn = {
- order: TurnOrder.DEFAULT,
+ order: TurnOrder.CONTINUE,
}
```
If currently not setting a …
=> Increment current player at start of phase in TurnOrder.DEFAULT

docs/documentation/stages.md, src/ai/ai.test.js, src/core/flow.js, src/core/flow.test.js, src/core/turn-order.js, src/core/turn-order.test.js
Supersedes #514, related to #487.
In order to clarify who is being impacted by `setActivePlayers` calls — especially in hooks — this changes the syntax to require a `currentPlayer` option instead of a `player` option:
Anyone currently using the `setActivePlayers` event or the `turn.activePlayers` option in their game config, who is using a `player` option may see breaking changes.
Migrating will take one of two forms:
1. #### Switching to using `currentPlayer`
For `turn.activePlayers` or `setActivePlayers` calls where `player` was always the current player in any case, users will only have to rename the option:
```diff
activePlayers: {
- player: 'A',
+ currentPlayer: 'A'
}
```
2. #### Maintaining `player` behaviour
For `setActivePlayers` calls where the behaviour impacted the player who …
=> Replace `player` with `currentPlayer` option in `setActivePlayers`

src/core/events.js, src/core/flow.test.js
Closes #482
Closes #487
The `update` method of the `Events` class currently caches the length of the event dispatch queue before processing it, avoiding processing of any new events pushed during processing.
https://github.com/nicolodavis/boardgame.io/blob/e20aca433f758ab66eaabbd077f61cebc25a9575/src/core/events.js#L42-L44
This seems sensible as it limits the scope of `update ` and presumably guards against infinite loops. However, this also causes the bug that events triggered _after_ a move, i.e. in hooks, are never processed and discarded.
This PR adds a test for the expected behaviour and simply removes the caching of the queue length, meaning now those new events are handled correctly. All tests are passing, but if you think there’s a risk making this change, let me know.
--- …
=> Fix events in hooks triggered by a move

src/client/debug/Debug.svelte
Currently `<button>`, `<section>`, and `<select>` elements in the Debug panel are being styled directly with global scope. This poses a fairly high risk of leaking styles to elements in the rest of an app using the debug panel.
This PR restricts the scope of those global selectors to only apply to children of the root debug panel component.
=> refactor(client): Scope global CSS selectors in Debug panel

src/server/api.test.js, src/server/api.ts
The intended behaviour of the server is to delete persisted game data when all players leave the game. When deleting the game data, the database implementation is currently passed the wrong ID, so the game data is never deleted, only the metadata. This PR fixes this bug.
=> fix(server): Use namespaced ID to delete persisted game data

src/master/master.js, src/master/master.test.js, src/server/index.test.ts, src/server/index.ts
Following on from #532, this adds a test for the wrapper used around users’ `authenticateCredentials` methods.
=> refactor: Harmonise Master’s auth signature with authenticateCredentials

src/plugins/plugin-player.js, src/plugins/plugin-player.test.js
This closes #530 and follows from some [discussion on Gitter](https://gitter.im/boardgame-io/General?at=5e409fefb612cc7bb1593457).
When the game definition included a `phases` section, the state expected from the PluginPlayer’s setup method was being overwritten with `undefined`.
The player plugin wraps moves with a modified `G`, adding a `player` and (for 2-player games) `opponent` field from `G.players`, then restores their values to `G.players` after the move.
For some reason, [the `turn.onBegin` function called in `StartTurn`](https://github.com/nicolodavis/boardgame.io/blob/b0a5175eb6a7a3656623a6ced640a9c6c3a741ef/src/core/flow.js#L324) is wrapped _twice_. I still don’t quite understand why, or why this only happens when phases are defined, but here is the result of a `console.trace` …
=> fix(plugins): Fix PluginPlayer setup

docs/documentation/testing.md
.connect() has been renamed to .start() in 2f86d92
=> fix local multiplayer test example

docs/documentation/multiplayer.md
Add `import React from 'react';` 
needed to avoid `'React' must be in scope when using JSX  react/react-in-jsx-scope` error.
=> Add missing import in multiplayer documentation

src/master/master.js
Credentials are only used to check if an action is authorized in the master and should not then be passed on to the reducer etc.
This contributes towards #227, because now credentials should not leak beyond the `Master.onUpdate` method and won’t end up for example in the game log.
=> fix(master): Remove credentials from action payloads after use

src/master/master.ts, src/server/api.ts, src/server/db/base.ts, src/server/db/flatfile.test.ts, src/server/db/flatfile.ts, src/server/db/inmemory.ts
This PR uses a generic type to model how `fetch` returns a selection of data fields based on the options object.
```ts
const data = db.fetch(gameID, { log: true });
// typeof data = { log: LogEntry[] }
```
It does add a little extra complexity in places where `let` is used before the fetch is called, but I think it might be a helpful tool.
Here’s some background: https://github.com/pirix-gh/ts-toolbelt/issues/98
---
As an aside, what is the value in maintaining async and sync APIs as separate interfaces? Can’t the in-memory database be implemented with async functions even if they are internally synchronous? It would simplify the codebase in quite a few places if it didn’t have to decide whether to `await` or not.
=> feat(server): Type fetch so that it returns what the opts request

package-lock.json, package.json, src/types.ts
This PR makes three small improvements to how types are published and contributes towards #576. (I think only server types still need to be exposed.)
1. Moved `ts-toolbelt` from `devDependencies` to `dependencies`.
While working with 0.39.2, I got errors because `ts-toolbelt` wasn’t installed and the exposed types depended on it.
2. Added a `types` field to the main boardgame.io package.json. Now the basic types in `src/types` can be consumed more simply:
```ts
import { State } from 'boardgame.io';
```
3. Imported and exported the storage API types (`FetchResult` etc.) in `src/types` so they can be used in third-party database connectors:
```ts
import { StorageAPI } from 'boardgame.io';
const opts: StorageAPI.FetchOpts = { state: true };
```
=> Typescript improvements

src/master/master.ts, src/server/api.test.ts, src/server/db/base.ts, src/server/db/flatfile.test.ts, src/server/db/flatfile.ts, src/server/db/inmemory.ts
~~Move the log concatenation logic out of `setState` and into a separate `appendLog` method.~~
Add a `deltalog` parameter to the `StorageAPI.setState` method to make it more obvious that `setState` should also handle appending entries to the game log.
Closes #577.
=> refactor(db): Make log handling explicit in StorageAPI.setState

src/server/db/base.ts, src/server/db/inmemory.ts
The database interfaces currently declare the `listGames` method as requiring an options object which can optionally include a `gameName`. The options object itself should be optional so we don’t have to do `listGames({})`. (This isn’t an issue with internal boardgame.io code, because it doesn’t currently use Typescript’s strict mode, but this helps for external libraries that do.)
=> fix(db): Make listGames options optional

src/plugins/plugin-events.ts, src/plugins/plugin-player.ts, src/plugins/plugin-random.ts, src/types.ts
When using the typings of `Ctx` I noticed it was missing the events. After having a look into the source code, I realized the `random` and `player` plugins also enhance the `Ctx` interface.
The name plugin implies that they are not necessarily defined, so I declared them optional.
Also it seems like specific event functions can be deactivated, so I declared those functions all optional as well. This has the downside, that you need to add checks or non-null assertions to your typescript code when calling those event functions.
=> add plugin types to ctx interface

src/core/flow.ts, src/core/game.ts, src/core/reducer.ts, src/plugins/main.ts, src/types.ts
This replaces places where `Function` (the Javascript function constructor) was used as a type with actual function types, trying to be as accurate as possible about the expected function signatures. It might be worth double checking in case I’ve mis-typed something.
Example of what I mean by `Function` constructor vs function type:
```diff
- interface Foo { fn: Function }
+ interface Foo { fn: (...args: any[]) => any }
```
Fixes #587.
=> feat(types): Replace Function constructor typings with function types

docs/documentation/plugins.md, src/core/game.ts, src/core/initialize.ts, src/core/reducer.ts, src/plugins/events/events.ts, src/plugins/main.ts, src/plugins/plugin-events.ts, src/plugins/plugin-immer.ts, src/plugins/plugin-player.ts, src/plugins/plugin-random.ts, src/types.ts
I used the `Plugin` type to enforce the type of the bundled plugins and that revealed some inconsistencies between the typing and the implementations, which I’ve tried to iron out.
- The events plugin expects a player ID to initialise its API, but the `Enhance` method didn’t receive or pass a player ID.
https://github.com/nicolodavis/boardgame.io/blob/9046ad1120a86bef6f25e6d32a9cc6021b2a9cbe/src/plugins/plugin-events.ts#L33-L35
https://github.com/nicolodavis/boardgame.io/blob/9046ad1120a86bef6f25e6d32a9cc6021b2a9cbe/src/plugins/main.ts#L139-L144
I’m not sure, but I wonder if this might explain #570, because the automatic game events might not function correctly if the events code isn’t receiving a player ID.
I’ve added `playerID` to the `Enhance` call sites, but it will be undefined when …
=> fix(plugins): More Typescript & pass playerID to Enhance

src/core/logger.ts, src/core/player-view.ts, src/core/turn-order.ts, src/types.ts
I’ve converted the turn order code to Typescript, in the process typing the turn order config object.
I’ve also added logging when `first` or `next` don’t return numbers as suggested in #586.
Between Typescript type checking and error logging, hopefully this will help people debug errors in their turn order settings.
=> refactor(core): More Typescript conversion

docs/documentation/storage.md
Adds a “caching” section to the storage docs, linking to `bgio-storage-cache`.
=> docs(storage): Document bgio-storage-cache module

docs/documentation/plugins.md, src/plugins/plugin-player.test.js, src/plugins/plugin-player.ts, src/types.ts
This removes the `playerSetup` function from the game configuration object. Instead, `PluginPlayer` should be called with an options object containing the setup function and it will return the plugin object boardgame.io expects.
**BREAKING CHANGE:** The `PluginPlayer` is no longer a plain object that looks for `game.playerSetup` during its setup. Instead, you have to call it, passing your setup method in an options object to the plugin:
```js
import { PluginPlayer } from 'boardgame.io/plugins';
const playerSetup = (playerID) => ({ ... });
const game = {
name: 'my-game',
plugins: [
PluginPlayer({ setup: playerSetup }),
],
};
```
Closes #603.
=> feat(plugins): Make player plugin a factory function

docs/documentation/api/Lobby.md
This will save time for many users when building their games.
Other Lobby API's are using query parameters, while this one is using body params.
This was confusing.
=> Specify type of parameters when joining game

src/core/turn-order.ts, src/types.ts
Fixes a bug raised by @flamecoals in #605 where an error is logged if `turn.order.next` returns undefined, which is permitted as a way of ending the phase.
I’ve also amended the turn order interface to indicate that `next` can return undefined.
=> fix(core): Don’t error if turn.order.next returns undefined

src/client/client.js, src/core/action-creators.ts, src/master/master.ts, src/types.ts
If playing on a remote server, actions are validated wrt player
credentials that are assumed to be inside action.payload.credentials:
https://github.com/nicolodavis/boardgame.io/blob/v0.39.3/src/master/master.ts#L188
However, in case of undo and redo, the client sends an action that
consists only of type:
https://github.com/nicolodavis/boardgame.io/blob/v0.39.3/src/core/action-creators.ts#L97
Make it possible to undo/redo with a remote server and fix #593 by
adding credentials to undo/redo actions.
* [v] Use a separate branch in your local repo (not `master`).
* [v] Test coverage is 100% (or you have a story for why it's ok).
=> Include credentials in undo/redo actions

docs/documentation/api/Client.md
* [] Test coverage is 100% (or you have a story for why it's ok).
I found the [credentials prop](https://github.com/nicolodavis/boardgame.io/blob/78729ebe9425a79ce65d76d1ae72211f8a17e726/src/client/react.js#L58) of the `WrappedBoard` react component returned by the Client not to be mentioned in the docs.
=> add documentation on WrappedBoard's missing `credentials` prop

src/server/api.test.ts, src/server/api.ts
DB adapter expects a hash containing `gameName` attribute for listGames method. This PR fixes DB call when indexing game rooms.
Closes: #620
=> Fix passing params to db adapter

scripts/clean.js, scripts/proxy-dirs.js
Mirrors how the other subpackages are bundled by exposing `boardgame.io/server` via a directory with a package.json that includes a pointer to the main entrypoint and the server type definitions. Addresses issues discussed in #576 and https://github.com/nicolodavis/boardgame.io/issues/190#issuecomment-612862456.
(I’ve also refactored the `proxy-dirs` code quite a bit, so feel free to pull me up on that if there’s something you’d prefer done in another way.)
=> build(server): Proxy server module with package.json

src/types.ts
This is available and used in several games on FBG right now:
https://github.com/freeboardgames/FreeBoardGames.org/blob/df037cc12e21948acfb63a90e6dd4cb088851ea4/src/games/takesix/game.ts#L50
https://github.com/freeboardgames/FreeBoardGames.org/blob/6317daad1079430257dc2648b85c61e393a071fd/src/games/secretcodes/util.ts#L11
It is especially important for knowing which user played when multiple users can play in the same turn (the currentPlayer in that case does not mean much)
=> Adding playerID to Ctx

docs/documentation/deployment.md
Tried the new method of deployment described in the `deployment` document, but it failed at first - I had to explicitly install `koa-static` and `koa-mount` packages to make it happen.
=> Adjust new deployment doc by adding necessary npm packages

CONTRIBUTING.md
In d463b00 the roadmap file was moved to the top level of the repository. However, the link to the roadmap in the contribution guide wasn't updated. This commit fixes the link and ensures that the roadmap document is easily accessible from the contribution guide.
=> Fix link to roadmap

docs/documentation/api/Server.md, src/server/index.ts, src/server/transport/socketio.js
This commit adds the option to run the boardgame.io server over HTTPS by passing through [koa-socket-2 SSL options](https://github.com/ambelovsky/koa-socket-2/blob/3c4433e/README.md#https-example) to the SocketIO transport.
While it's also possible to achieve HTTPS in other ways, e.g. via nginx as discussed in https://github.com/nicolodavis/boardgame.io/issues/322, enabling first-party support for HTTPS makes it much simpler to spin up such services since it removes the need to install and configure an external SSL terminator and proxy.
=> Add option to run server over HTTPS

docs/documentation/api/Game.md, src/core/flow.test.js, src/core/flow.ts, src/types.ts
This implements a long-form move syntax that prevents a move from incrementing `numMoves` and by extension triggering move limits. It would close #644.
This is a slightly naïve way of implementing this `noLimit` feature because as a consequence we completely lose track of those moves in the move counts. In theory we could track `numMoves` and `limitNumMoves` separately and trigger move limits using the latter, but it would make state and logic more complex. Let me know if you think it’s acceptable as is or if we should implement the more robust version.
=> feat(core): Support moves that don’t contribute to numMoves

docs/documentation/api/Lobby.md, src/server/api.test.ts, src/server/api.ts, src/types.ts
This commit adds an option to game room creation to mark the room as unlisted. Unlisted rooms are excluded from the list of all rooms. The setting is useful for situations where someone wants to host a room for friends and therefore doesn't want arbitrary people to be able to join their room via the lobby.
=> feat(server): Add option to exclude rooms from public listing

src/server/api.test.ts
This is a replacement of #654 and a follow-up to #642.
=> Test warning is logged when using deprecated `/rename` API endpoint.

docs/documentation/multiplayer.md
The MongoDB adapter was removed relatively recently from the project, but the multiplayer documentation implies that it still exists.
This PR removes that part from the docs.
=> [Documentation] Remove references to removed MongoDB adapter

docs/documentation/phases.md, src/core/flow.ts, src/types.ts
This adds more detail to the “Moving between phases” section of the documentation to clarify how to return a `{ next }` object from a phase’s `endIf`.
I’ve also updated the types to reflect that `endIf` can return `{ next }`.
=> docs(phases): Expand documentation of phase.endIf

src/server/api.test.ts, src/server/api.ts, src/types.ts
There are quite a few changes here, but most are housekeeping/refactoring:
- **feat:** Improve/tighten game creation options checking (ca819d9)
- Centralise setting default `numPlayers` in `CreateGame` method
- Only add `setupData` field to game metadata if not undefined
- Ensure `unlisted` field is always a boolean value
- Fixes delucis/bgio-firebase#4
- **feat:** Use the `createGame` storage API when creating a game. (I guess this was missed somehow when the new API was implemented.) (40f1d7b)
- **feat:** Throw 404 error from `create` endpoint if the game name isn’t found (da8a473, a90ea78)
- **refactor:** Improved typings (af72f03, 88a75d6)
- **test:** Tidied up some of the API tests (3a00357, 09f2336, 67090d2)
=> feat(server): Lobby API improvements

docs/documentation/tutorial.md
create-react-app recommends using npx to create a new application:
https://create-react-app.dev/docs/getting-started#quick-start
> If you've previously installed create-react-app globally via npm install -g create-react-app, we recommend you uninstall the package using npm uninstall -g create-react-app to ensure that npx always uses the latest version.
=> Update create-react-app's installation command

docs/documentation/index.html, docs/documentation/sidebar.md
This PR adds the pagination plugin to the docs, following the conversation in #683.
While testing the docs manually, I noticed that the pagination was not showing up when accessing the documentation's `homepage` from the "Documentation" link on the homepage.
So I spent some time figuring it out and the problem comes from the fact that the documentation's `homepage` has two URLs: `/` and `/README`. This issue has been reported in [docsifyjs#1131](https://github.com/docsifyjs/docsify/issues/1131) and the recommended solution is to change the link to the homepage in the sidebar from `concepts.md` to `/`.
I updated the sidebar and it does work now. I also tested the old URL (`/README`) to make sure that it still works and it does. The pagination is not showing up on `/README` though. It's …
=> Add pagination plugin to the docs

src/plugins/plugin-immer.test.js, src/plugins/plugin-immer.ts
Closes #687
This changes the immer plugin to handle returning `INVALID_MOVE` after mutations have already been applied to `G`. This is different from the approach I initially considered in #687, but is actually conceptually a little simpler.
Basically, if a move returns `INVALID_MOVE` we return `undefined` to immer, which therefore accepts any state mutations, but still return `INVALID_MOVE` instead of the bad state update to the reducer.
=> feat(plugins): Let moves return INVALID_MOVE after mutating G

packages/core.ts, src/core/constants.ts, src/core/game.ts, src/core/reducer.test.js, src/core/reducer.ts, src/plugins/plugin-immer.test.js, src/plugins/plugin-immer.ts, src/types.ts
This moves the `INVALID_MOVE` constant to a separate file to fix the circular dependency introduced in #688.
=> fix: Move INVALID_MOVE constant to avoid circular dependency

docs/documentation/api/Lobby.md, docs/documentation/api/Server.md, src/server/api.test.ts, src/server/api.ts, src/server/index.test.ts, src/server/index.ts, src/types.ts
This pull request refactors `Server.run` to separate setting up the API routes from running the API server. Splitting these responsibilities enables developers to more easily customize hosting of the app, e.g. customizing the CORS setup, mounting the API routes at a path prefix, etc.
=> feat(server): Expose API router

src/server/db/flatfile.ts
A problem in node-persist, used by FlatFile, means multiple async read/writes to the same file are allowed (no file-locking) and can and does cause corruption (which may or may not be caught) in higher frequency situations.
This PR uses a Promise chain to ensure only one async read/write is performed at a time. The queue is rather crude, but does guarantee no multiple writes (if only one FlatFile instance is being used on that directory).
In the future it would be nice to have Promise chain per-file, or seek alternatives to node-persist.
However, for now, this solution has been working for my own project and it's probably worth the added protection vs the potential performance loss.
---
Closes #694
=> Use Promise chaining to enforce read/write queue

src/server/api.test.ts, src/server/api.ts
This adds the `gameover` metadata, if it exists, to both the all rooms and single room query endpoints.
Fixes #665.
=> fix(api): Expose gameover metadata in rooms endpoints.

src/server/db/flatfile.ts
After looking over the original solution, it seemed wasteful not to have it work at a per-file level.
Especially considering how many files bgio can generate *per match*. Projects with large numbers of on-going matches could suffer unnecessary delays.
This performance tweak gives each node-persist key (and therefore file) a Promise chain. Allowing every file to be read/written async, without concern for corruption.
I've also abstracted away the 'chaining' behavior here, so the user just calls getItem/setItem as they would normally to a node-persist object. Removes boilerplate and potential human error.
Bug fix: I noticed an issue in 0.39.10 where the initialstate didn't appear to get written to disk. In .11 it does correctly. However that exposed another issue, the initialstate file …
=> FlatFile - Per-file request queues enhancement

docs/documentation/api/Client.md, docs/documentation/api/Lobby.md, src/lobby/connection.js, src/lobby/connection.test.js, src/lobby/create-match-form.js, src/lobby/match-instance.js, src/lobby/react.js, src/lobby/react.test.js, src/lobby/room-instance.js, src/master/master.test.ts, src/master/master.ts, src/server/api.test.ts, src/server/api.ts, src/server/db/base.ts, src/server/db/flatfile.test.ts, src/server/db/flatfile.ts, src/server/db/inmemory.test.ts, src/server/db/inmemory.ts, src/types.ts
Here's where I'm at with this work. I've tried to do it slowly, with a lot of small, focused commits, to make this easier to review. I know how painful this type of change is to review, sorry in advance! :)
I believe this covers all of the instances of "room" in the api and lobby, as well as all the cases where "game" was used but it actually meant "match". It is, however, likely that I have missed some instances in some corners of the app. I'm counting on you to spot them! :grin: 
Regarding documentation, I guess we'll want to explain the changes very clearly. Should that be in the changelog? I want to wait until these changes are validated before writing that doc though.
=> Fix #703 - Use the term "match" in the API and Lobby

src/server/index.test.ts, src/server/index.ts, src/server/transport/socketio.test.ts, src/server/transport/socketio.ts
Allows using socket adapter, that's one possible solution for horizontal scaling issues.
The issue where this is requested: https://github.com/nicolodavis/boardgame.io/issues/534
More information about socket.io-adapter option: https://socket.io/docs/server-api/#server-adapter-value
=> Add support for socket.io-adapter implementations

src/client/debug/main/Controls.svelte
Fixes #711
As far as I know, can't expect Restore function from svlete file, so can't test that function. See issue for more.
=> Resolves issue #711 - Fix restore in debug controls

docs/documentation/api/Lobby.md, src/server/api.test.ts, src/server/api.ts
From https://github.com/nicolodavis/boardgame.io/issues/718
When hitting the lobby/playAgain API, uses `setupData` and `numPlayers` values from the specified previous game unless they are explicitly overridden. 
Update docs to reflect this.
=> feat(lobby): playAgain endpoint uses previous game config as defaults

src/ai/ai.test.ts, src/ai/ai.ts, src/ai/bot.ts, src/ai/mcts-bot.ts, src/ai/random-bot.ts, src/types.ts
This is a straight conversion of the AI code to Typescript.
- The key detail is that now the base `Bot` class is declared as an abstract class, specifying the expected signature of the `play` method extending bots should implement. I’ve marked all class fields & methods as private or protected wherever possible.
- Improved the `ai.enumerate` type in the Game definition.
- Fix: `bot.random()` will now return `undefined` if passed an empty array (instead of `Math.floor(number * [])`)
- Fix: `objectives` is consistently called with `playerID` in the MCTS bot
=> refactor(ai): Convert to Typescript

README.md, docs/documentation/deployment.md, docs/documentation/multiplayer.md, docs/documentation/storage.md, docs/documentation/tutorial.md, docs/index.html
npm install executes "--save" by default since npm v5.0.0.
Links:
https://github.com/npm/npm/releases/tag/v5.0.0
https://blog.npmjs.org/post/161081169345/v500
> npm will --save by default now. Additionally, package-lock.json
> will be automatically created unless an npm-shrinkwrap.json exists.
I've left out `integration/README.md` and `node_modules/`.
=> Remove --save option from npm install occurrences

package-lock.json, package.json, src/master/master.test.ts, src/master/master.ts, src/server/api.test.ts, src/server/api.ts, src/server/db/base.ts, src/server/db/inmemory.test.ts, src/server/db/inmemory.ts, src/types.ts
This PR ( based on issue #735 ) adds `createdAt` and `updatedAt` fields to the metadata containing numeric timestamps. Furthermore, the following query parameters were given to the listGames endpoint: `isGameover`, `updatedBefore`, `updatedAfter`.
=> allow to filter listGames query

src/client/debug/main/Controls.svelte
I didn’t check #712 and #716 thoroughly enough and they hadn’t completely fixed the save & restore bugs. This PR does the following:
- Include empty log and undo/redo arrays in the saved game state to fix the client throwing on restore because `state._undo` is undefined (for example).
- Persist the game’s initial state (under a separate local storage key), so that reset continues to work after a page refresh and save state restore.
=> fix(debug): Fix save & restore in Debug panel

docs/documentation/notable_projects.md
I developed a 2-player strategy game called Thinktank using boardgame.io. It's an online adaptation of a board game called Conundrum, which was designed by some alumni at my university.
It would be awesome to have Thinktank added to the notable projects list!
=> docs: Add Thinktank to notable_projects.md

docs/documentation/api/Lobby.md, docs/documentation/api/Server.md, packages/client.ts, src/lobby/client.test.ts, src/lobby/client.ts, src/lobby/connection.test.js, src/lobby/connection.test.ts, src/lobby/connection.ts, src/lobby/react.ssr.test.js, src/lobby/react.test.js, src/server/api.ts, src/types.ts
This PR adds:
- Types for the data returned by the Lobby API, closing #707
- A new plain JS lobby client class that is a lightweight wrapper around `fetch` and provides end-to-end typing for TS users
- It also refactors the React Lobby’s connection class to use the new plain client, which makes that class a little easier to understand.
=> feat: Add plain JS lobby client

CONTRIBUTING.md, README.md, docs/documentation/CHANGELOG.md, docs/documentation/index.html, docs/documentation/storage.md, docs/index.html, package.json, roadmap.md, scripts/changelog.js
- Replaces references to `nicolodavis/boardgame.io` with `boardgameio/boardgame.io`
- Fixes status badges on docs homepage for new CI set-up
=> chore: Tidy up after moving repo to org

package-lock.json, package.json, src/client/client.ts, src/types.ts
This PR fixes a couple of small issues with how types for boardgame.io are provided:
1. Move the `import 'svelte'` added in #752 to `src/client.ts` instead of in the top-level types file. The Svelte types depend on various browser built-in types (`HTMLElement` etc.), which a consumer may not have in their TS environment if they are building something like a database connector or a plugin. They could add `"lib": ["dom"]` in their tsconfig.json, but that seems wrong situations like these. Moving the import to the client ensures it only comes into scope for projects that actually need it.
2. Move `@types/koa` from `devDependencies` to `dependencies`. We expose some types that use the Koa context type, so consumers need these type declarations installed too (which makes sense seeing as `koa` …
=> fix: Tidy up type provision

rollup.config.js
Fixes #766
@nicolodavis I’ve found it a little tricky to test this, but looking through the bundle output, this removes the Svelte imports introduced in 0.39.15, and I could get a demo project to build. Sorry for all the false starts getting the Svelte–Typescript integration working, I’ve been learning the hard way to double check my work…
=> build: Exclude svelte from Rollup’s external module list

src/client/debug/Debug.svelte
Only change here is adding `z-index` to alter the debug-menu render height.
Fixes #778
=> Enforce that the debug menu is always on the top of the screen

docs/documentation/secret-state.md
Remove an out-of-date instruction to import `Game` and call it with the game definition in the secret state docs (as spotted [on Gitter](https://gitter.im/boardgame-io/General?at=5f487f8136e6f709fd0911da)).
=> docs(secret-state): Fix obsolete reference to importing `Game`

package.json, src/client/debug/main/Main.svelte, src/client/debug/tests/JSONTree.mock.svelte, src/client/debug/tests/debug.test.js
In #781, I decided we could use `require` to always depend on the compiled JSON Tree component we were adding (rather than the Svelte source files). However, after manual testing I see that this causes runtime errors when the tree component unmounts (for example when toggling to the AI or Info panels). As far as I understand, this is due to the Debug panel and the third-party component depending on different copies of Svelte internals, which causes problems ([this explanation](https://github.com/sveltejs/svelte/issues/3671#issuecomment-544329688) helped me).
So, we need to depend on and compile the Svelte component ourselves to fix this, but that caused test errors (as detailed in #781). To resolve this, I’m now mocking the tree component in tests. I *think* the errors might be because of …
=> fix(debug): Fix runtime error introduced by #781

src/client/debug/Debug.svelte, src/client/debug/info/Info.svelte, src/client/debug/main/InteractiveFunction.svelte, src/client/debug/main/Main.svelte, src/client/debug/main/PlayerInfo.svelte, src/client/debug/utils/shortcuts.js, src/client/debug/utils/shortcuts.test.js
This PR pulls together some small features and bug fixes to improve the debug panel:
- Add keyboard shortcuts for game events. Instead of “End Turn” etc. being shown as buttons, they are rendered using the same component as moves (supporting argument input). I’ve assigned the shortcuts <kbd>7</kbd>, <kbd>8</kbd>, <kbd>9</kbd> for these. (c5683da, e107103)
- Support dispatching moves as any active player when using stages (as requested in #771). (03f7b2c)
- Make the player ID buttons keyboard accessible. This isn’t quite the same as adding a shortcut for toggling through player IDs, but it seems a fairly good solution to tab through and activate the desired ID. (9a640c4)
- Fix a logic bug in the Info pane. (e757efe)
- Fix a bug when the interactive function component received focus using …
=> feat(debug): Events shortcuts, stages support & minor fixes

docs/documentation/notable_projects.md, src/server/db/flatfile.test.ts, src/server/db/flatfile.ts
=> fix: FlatFile.listGames filter

src/core/flow.ts
A side effect of calling `EndPhase()` is an automatic call to `EndTurn()`. LogEntries for `endPhase` and `endTurn` log entries are added to `deltalog`.
When the user mouses over `LogEntries` in the **Debug Panel**, the state is regenerated/reduced from the deltalogs. `EndPhase()` *again* makes an automatic call to `EndTurn()`, and then the `endTurn` in the `deltalog` is also called, resulting in
one-too-many calls to `EndTurn()`.
This issue affects games using `DEFAULT` turn order and causes playback fail when using the `Debug:Log` Panel.
This error is generated to the browser console:
```
ERROR: disallowed move: MYMOVENAME
```
where *MYMOVENAME* is the name of the move that fails.
Appears to correct issue #810
Issue also reported:
* [Gitter 2020-06-23 …
=> fix(core): Fix EndPhase deltalog

src/server/transport/socketio.ts
=> fix: improve socketio.ts typings

docs/documentation/notable_projects.md, src/client/client.test.ts, src/client/client.ts
Fix #818 
This fix disable strip on client if current client is multiplayer .
=> fix(client): Fix playerView executed twice do not strip again if is multiplayer

src/core/reducer.ts
Fixes #795
The move reducer currently increments `_stateID` before events (and other plugins) are processed, potentially resulting in deltalogs as follows:
```js
[
{ action: { type: 'MAKE_MOVE' }, _stateID: 2 },
{ action: { type: 'GAME_EVENT' }, _stateID: 3, automatic: true }
]
```
This was causing bugs on the client, because the next move might produce a deltalog like:
```js
[
{ action: { type: 'MAKE_MOVE' }, _stateID: 3 }
]
```
This [is filtered out by the client](https://github.com/boardgameio/boardgame.io/blob/0062e5508f0e8f86c9bf9f60bd4da0c641b7e184/src/client/client.ts#L218-L222) because the `_stateID` is considered stale.
This fix ensures that `_stateID` is only incremented _after_ plugins run, so that log entries for a single action all share the same ID. For multiplayer clients, …
=> fix(reducer): Fix stateID increment & build deltalog on server only

src/master/master.test.ts, src/master/master.ts, src/server/api.ts, src/server/util.ts
Closes #722 
This makes implicit match creation in the master consistent with match creation via the Lobby API by using the Storage API’s `createMatch` method and creating basic match metadata even for these implicitly created matches. (It helps that we can now mark these matches as unlisted just in case someone was mixing the Lobby API & implicit match creation.)
Apart from the consistency, this also fixes a bug by ensuring that `initialState` is stored for implicitly created matches. Previously, by only using `setState`, clients couldn’t retrieve `initialState` for matches that had been initialised in this way, because it was never stored.
=> fix(master): Use `createMatch` for implicit match creation

src/core/flow.test.js, src/core/flow.ts, src/core/initialize.ts, src/core/reducer.test.ts, src/core/reducer.ts, src/master/master.test.ts, src/master/master.ts, src/types.ts
- Add plugins state and playerID to undo/redo entries.
- Only allow players to undo/redo their own actions.
- Improve undo/redo validity check in master (fixes #565).
=> feat: Improve undo/redo

src/client/client.ts, src/client/debug/log/Log.svelte, src/client/debug/log/LogEvent.svelte, src/core/reducer.test.ts, src/core/reducer.ts, src/types.ts
Closes #820
- Add `deltalog` entries when processing undo/redo actions.
- Add undo/redo `deltalog`s to the client’s log.
- Display all non-automatic actions in the debug panel’s log pane.
- Use “assumed” `playerID` for undo/redo dispatchers on the client (i.e. if `playerID` is null/undefined for a single-player client, use `currentPlayer`).
=> feat: Add log entries for undo/redo actions

src/client/client.ts, src/lobby/connection.ts, src/lobby/create-match-form.tsx, src/lobby/login-form.tsx, src/lobby/match-instance.tsx, src/lobby/react.ssr.test.tsx, src/lobby/react.test.tsx, src/lobby/react.tsx, src/types.ts
Similar to @coyotte508 in https://github.com/boardgameio/boardgame.io/issues/190#issuecomment-617446765, I recently ran into an issue importing `boardgame.io/client` due to the missing types in the Lobby React components. As such, this pull request converts the Lobby React components to Typescript which should fix the import error.
=> refactor(lobby): Convert React components to Typescript

docs/documentation/api/Game.md, src/server/api.test.ts, src/server/api.ts, src/types.ts
Many games have complex rules which affect configuration or setup options. For example, Sushi Go Party ([see rules](https://gamewright.com/pdfs/Rules/SushiGoPartyTM-RULES.pdf)) allows the Edamame card to only be used when there are 3 or more players in the game or the Menu card when there are 6 or fewer players in the game. To enable games to feed back these sorts of validation results to the client, this pull request introduces a new exception type `GameSetupError` which game setup code can throw to indicate an incompatible configuration. If thrown, the exception is communicated back to the client as a HTTP 400 error.
=> feat(server): Enable game setup to perform validation

src/client/transport/local.test.js, src/client/transport/local.ts
This returns a shared local master from the Local transport even when `bots` is passed in the options to `Local`. #553 changed this to avoid  out-of-date bots persisting, but in the process broke scenarios where  several clients should remain in sync on a single page (see #800). This  implements a more careful check, returning a shared master as long as  the `bots` options passed are *equal* to each other (via simple object  equality).
The reliance on object identity could still represent a confusing  gotcha, so in the future it might be better to offer a more explicit  API for getting a new clean transport. Moving the global map of master  instances *inside* the function scope of `Local`, could do this —  calling `Local` would always return a new transport layer that could  be shared …
=> fix(local): Use shared local master with bots

docs/documentation/api/Client.md, src/client/client.ts, src/client/transport/socketio.test.js, src/client/transport/socketio.ts, src/master/master.test.ts, src/master/master.ts, src/server/transport/socketio.test.ts, src/server/transport/socketio.ts, src/types.ts
Closes #834 
- Server now keeps track of all players connection status and stores this information in `matchData` alongside `id` and `name`
- Every time player connects or disconnects from the SocketIO server, `onConnectionChange` method is called on `Master` to update players metadata in `DB` and broadcast that info to all the players in the match as `matchData` message
=> feat: Track players connection status (#834)

.github/workflows/npm-publish.yml
This PR adds a GitHub workflow file that will run for new git tags on the master branch that have the form `v0.x.x`.
The workflow will:
1. Run unit tests as a safety check.
2. Try to publish to npm, using [this GitHub Action](https://github.com/marketplace/actions/npm-publish?version=v1).
If desirable, we could set `dry-run: true` on the publish step to test out the command before running it for real.
This workflow is only responsible for publishing to npm. Tagging a new release, updating the changelog etc. must still be done locally.
=> ci(Github): Add npm publish workflow

docs/documentation/notable_projects.md
Adding [cantstop.fun][1] to the notable projects list.
I wasn't exactly sure where to put it in the list: I followed the almost alphabetical order.
I'm happy to create a following PR sorting everything in alphabetical order if you folks think it's a good idea.
[1]: https://cantstop.fun
=> Add https://cantstop.fun to notable projects

src/client/debug/log/LogEvent.svelte
Fixes #855 
As discussed in the issue, handle the case in the debug panel where `args` is a string.
I manually tested it, now `endStage` events appear in log without crash.
=> Fix: endStage event crashes debug log panel.

docs/documentation/plugins.md, src/client/client.ts, src/master/master.ts, src/plugins/main.ts, src/plugins/plugin-player.test.ts, src/plugins/plugin-player.ts, src/plugins/plugin-random.ts, src/plugins/random/random.test.ts, src/types.ts
Closes #671
This PR adds a `playerView` option to the plugin API allowing plugins to filter their data before it is returned to clients in the same way a game’s `playerView` option can filter `G`.
It also adds a `playerView` that hides PRNG state from clients to the random plugin and a way for users to set a custom `playerView` for the player plugin.
=> feat(plugins): Add playerView option to plugin API (close #671)

src/client/client.ts, src/client/transport/local.ts, src/client/transport/socketio.test.ts, src/client/transport/socketio.ts, src/client/transport/transport.ts, src/master/master.test.ts, src/master/master.ts, src/server/api.test.ts, src/server/api.ts, src/server/auth.test.ts, src/server/auth.ts, src/server/db/base.ts, src/server/index.ts, src/server/transport/socketio-simultaneous.test.ts, src/server/transport/socketio.test.ts, src/server/transport/socketio.ts, src/types.ts
This is some fairly hefty refactoring, but it should have minimal user impact. Here’s the summary:
- This PR creates a new `Auth` class to hold credential generation & authentication logic. This is instantiated when creating a server instance and can be customised via the server options as was already possible.
- The `Auth` instance is passed to the lobby API replacing existing equality checks, allowing for custom authentication in the `leave`, `playAgain` and `update` endpoints. Closes #693.
- The `Auth` instance is passed to master instances that run on the server and is used to authenticate all methods rather than only authenticating `onUpdate`. Closes #840.
- Additional refactoring was necessary in the transport layers to send credentials for the `sync` event.
For most users, these …
=> feat: Centralise lobby API and master authentication logic

src/plugins/random/random.test.ts, src/plugins/random/random.ts
Fixes #870
Prior to the current plugin system, the randomness API set a default seed '0' if it didn’t receive one from game state (i.e. when it was run on a multiplayer client and the randomness state was redacted). When the new plugin system was built, this fallback value was removed, but that didn’t cause errors because the PRNG seed and state were no longer redacted. After #857 (released in v0.42.2) reintroduced redacted state for plugins, the plugin broke for multiplayer clients that no longer had access to plugin state.
This commit reinstates the default seed (the result of which is discarded in any case) and adds a test for running the plugin with redacted state to catch a similar error in any future refactoring.
See 4b1c1357403ff3449e37cdfa158587f911ae3d7b for details of the …
=> fix(random): handle redacted state on multiplayer clients

src/core/flow.test.ts, src/core/flow.ts
#788 "UnhandledPromiseRejectionWarning: TypeError: state.deltalog is not iterable"
Everywhere else that deltalog is updated, it uses this (state.deltalog || []) pattern.
=> Prevent TypeError: state.deltalog is not iterable

src/server/transport/socketio-simultaneous.test.ts, src/server/transport/socketio.test.ts, src/server/transport/socketio.ts
Closes #889
- Delay adding clients to `SocketIO#clientInfo` until after they have been authenticated.
- Improve transport API to avoid potential for a single event to trigger exponential numbers of emits.
- Add test cases for scenarios discussed in #889.
- Make process of adding and removing clients consistent across event handlers.
There is still no expiration of client connections, so hypothetically the transport is still vulnerable to a client that keeps open its connection after leaving a credentialed match that someone else then joins (see #889 for discussion). The only way to avoid that currently would be to re-authenticate each client when sending anything to them, which would add significant overhead to what is supposed to be a lightweight transport layer. I think ultimately there …
=> fix: Improve security of socket.io transport layer

packages/client.ts, src/lobby/client.test.ts, src/lobby/client.ts
This pull request customizes the error type used in `LobbyClient` to enable passing-through to callers additional details about the specific error that the client encountered. Amongst others, this behavior is useful in situations where the errors thrown by the Lobby API may contain remediation hints for the user. For example, when using custom setupData validation (see https://github.com/boardgameio/boardgame.io/pull/831), the errors returned by the API may contain instructions to the user setting up a game on what exactly is incorrect about their configuration.
An alternative implementation could also expose the `response` object directly on `LobbyClientError` which would allow more flexibility to callers but also increase coupling with the client's implementation (e.g. changing away …
=> Add details to exceptions raised in LobbyClient

src/core/logger.test.js, src/core/logger.ts
Closes #917 
Allows logging to be spied after the framework has been loaded. Eases testing of invalid moves.
=> Updating logging methods to be spied upon after framework is loaded. #917

AUTHORS, packages/plugins.ts, src/client/react.tsx
This fixes the issue I brought up in #190 where the `PlayerPlugin<T>` interface was not part of the public api.
Additionally, there is a second fix for a related issue I ran into when using the React `Client` component where the `game` property used only `Ctx` in the type signature instead of the generic type constraint `ContextWithPlugins`.
This caused the code setting up the client to not compile when plugins were used.
1. Create a game definition that uses `Ctx` extended with plugins:
```ts
interface CustomGameContext implements Ctx {
// Extend the context with properties and methods
}
const CustomGameDefinition: Game<any, CustomGameContext, any> = {
// game definition elided for brevity
};
```
2. Use the game definition with the React Client component:
```ts
const App = …
```
=> feat: improve typescript typings for the player plugin and react client component

src/plugins/main.test.ts, src/plugins/main.ts
This changes the order the plugins are flushed in to fix the problem mentioned in #910. It also adds a test to make sure it works.
This removes the additional reverse as it seemed necessary to separate PluginEvents from the rest (hence CORE_PLUGINS and DEFAULT_PLUGINS) to execute everything in the right order.
=> Fix custom plugins not available in events hooks. Add test.

src/core/reducer.test.ts, src/core/reducer.ts
See https://github.com/boardgameio/boardgame.io/pull/940#discussion_r637324455
=> [Bugfix] Events should be undoable

src/client/client.test.ts, src/client/client.ts, src/core/action-creators.ts, src/core/action-types.ts, src/core/errors.ts, src/core/reducer.test.ts, src/core/reducer.ts, src/master/master.test.ts, src/master/master.ts, src/plugins/main.ts, src/types.ts
This PR sets up the initial reducer/master plumbing for error handling
by introducing a "transients" option bag containing errors.
The goal of this change is to be as backwards-compatible as possible,
with subsequent changes building on top of the API extensions added
here.
Notes:
- Previously, there was an assumption that the state resulting from a
reducer processing an action is suitable for client consumption.
- Now, transient artifacts might be appended onto the state and need to
be stripped before being sent to the client.
- To work around this change, I added some new types to help signal
the "transient" nature of State that enters and exits the reducer.
- I'm assuming the master is the single caller of the core reducer and
leaving it up to the master to do this stripping..
=> feature(#723): Improve client error handling [Part 1]

docs/documentation/api/Server.md, package-lock.json, package.json, src/server/api.test.ts, src/server/api.ts, src/server/index.ts
#946 added an `origins` option to the server, which is used to enable CORS for the socket.io transport.
The Lobby API server currently uses `@koa/cors` with no configuration to reflect the request origin back in the `Access-Control-Allow-Origin` header, enabling requests from any origin:
https://github.com/boardgameio/boardgame.io/blob/2b1d013a03132d9d40c38c0d34b94e91d0a2509a/src/server/api.ts#L451
Given the server now *requires* setting origins, I thought we should probably also lock down the Lobby REST API to those same origins. This PR adopts the same method used by socket.io to validate request origins against the `origins` option for use with the `@koa/cors` middleware.
What do you reckon @vdfdev? Is there a chance the socket server and REST API need to allow access to different …
=> feat(server): Use `origins` option to configure Lobby API CORS

src/client/client.test.ts, src/client/client.ts, src/master/master.test.ts, src/master/master.ts, src/types.ts
#940 introduced an internal `STRIP_TRANSIENTS` action that strips error state from the final reducer output, so it can be used to trigger side effects. This action type was being included in the actions forwarded by the client to multiplayer transports. Because this action does not have a `payload` field, this caused the master to crash in various places were it assumed a `payload` object would be defined.
This PR adds logic to ignore the `STRIP_TRANSIENTS` object when forwarding actions to multiplayer transports.
For robustness, it also allows the master to gracefully handle cases where it receives an undefined `action` or `action.payload` as in theory crashing on undefined user input could be an attack vector.
---
CC: @shaoster
Reported [on …
=> fix: Don’t leak `STRIP_TRANSIENTS` action

docs/documentation/plugins.md, src/core/errors.ts, src/core/reducer.test.ts, src/core/reducer.ts, src/plugins/main.test.ts, src/plugins/main.ts, src/types.ts
Closes #962
This adds support for an `isInvalid` method in boardgame.io plugins. Similar to the current `noClient` plugin method, this allows the reducer to ask plugins if everything is OK or if the current event/move is invalid from their point of view. If one or more plugins returns a truthy value from its `isInvalid` method, the reducer will fall back to its initial state, analogous to what it does when a move returns `INVALID_MOVE`.
Currently this is not in use but the intention would be to use it for the events plugin, following on from #957. It also allows for other custom use cases, like state validators.
- `isInvalid` should return a string if the action is invalid. This could be less strict if that seems desirable.
- The error returned to the client is of the form
```js
{
type: …
```
=> feat: Allow plugins to declare an action invalid

docs/documentation/notable_projects.md, src/client/transport/local.ts, src/master/filter-player-view.test.ts, src/master/filter-player-view.ts, src/master/master.test.ts, src/master/master.ts, src/server/transport/socketio.test.ts, src/server/transport/socketio.ts
In this PR I refactor the interface between Master and Transport, so the Master will only send a single message to the transport, and then the transport will calculate the player view for each player. 
This will allow us to use a pub/sub to propagate the Master message, allowing us to scale the bgio server horizontally.
=> Refactor: Decouples player view calculation from Server's Master

src/core/initialize.ts, src/core/reducer.ts, src/plugins/main.ts
#963 introduced an `isInvalid` method to the plugin API allowing plugins to declare updates invalid. #963 used this to check updates in the reducer, but didn’t handle plugins being flushed during game initialisation. This PR refactors use of plugins so that flushing and validation always happens together via a consolidated `flushAndValidate` method.
---
It’s not quite clear at the moment how game initialisation should handle errors, so I’ve left that open for now — this allows plugins to revert plugin updates and log an error, but won’t actually break games. At some point it would be good to handle game initialisation errors properly.
=> feat(plugins): Consolidate flush and validate plugins

src/master/master.test.ts, src/master/master.ts
This line was throwing unhandled promise rejections when I was testing invalid packets
- [ this was edited in github] Use a separate branch in your local repo (not `main`).
- [no ] Test coverage is 100% (or you have a story for why it's ok)
=> fix(master): Don’t crash on missing chatMessage

docs/documentation/events.md, packages/core.ts, src/client/transport/local.test.ts, src/core/flow.test.ts, src/core/flow.ts, src/core/game-methods.ts, src/core/game.ts, src/plugins/events/events.test.ts, src/plugins/events/events.ts, src/plugins/main.ts, src/plugins/plugin-events.ts, src/types.ts
Here’s an attempt to close #979. Feedback very much wanted and if you want to pick this up and iterate on it, you’re welcome to as I likely won’t have much time in the next couple of weeks.
Also closes #981.
When wrapping game hooks (`onBegin`, `onMove`, `onEnd`), provide a unique string to the plugin interface so that it knows which hook is being wrapped. (These unique strings are from a kind of custom enum accessed like `GameMethod.Phase.ON_BEGIN` or `GameMethod.MOVE`.)
A plugin’s `fnWrap` then receives this string in addition to the function to wrap, so it can change behaviour appropriately.
```js
const plugin = {
name: 'discerning-wrapper',
fnWrap: (fn, fnType) => (...args) => {
if (fnType === GameMethod.Turn.ON_MOVE) {
console.log('Looks like this is an onMove hook.);
}
return …
```
=> feat: Expose method types to plugin `fnWrap` & improve events errors

src/types.ts
I'm fresh to this framework, so maybe I'm missing something. But this looks like a very small, simple improvement to the types 😊
=> fix(types): Expect Game.setup method to return G

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, CONTRIBUTING.md, README.md
No changes to source files, just configuration files for dev containers. This should make it possible for anyone to just fire up the repository in a container and run it. `devcontainer.json` currently contains a minimum of useful extensions for linting (eslint, prettier), contributing (gitlens, github PR) and developing (React snippets). 
Any suggestions for other default settings or extensions that would make development more consistent/uniform/easy?
=> chore: Add VS Code dev container support

package-lock.json, package.json, src/ai/mcts-bot.ts
Use `setImmediate` to run each async iteration of the MCTS bot. In most scenarios this will use a polyfill as `setImmediate` is not widely supported or on a web standards track. See <https://github.com/YuzuJS/setImmediate> for browser support details. This polyfill is pretty old and covers some use cases we don’t need — like Node < 0.9 (!!) — so maybe it would be preferable to roll our own smaller, simpler `postMessage`-based alternative? I tried this library as a proof of concept test, and it did seem to result in faster AI result times using the Tic-Tac-Toe example by maybe 30% (and actually more in later game stages with fewer game branches although at that point the perceived difference is not so significant).
=> perf(ai): Run AI iterations using `setImmediate`

src/lobby/client.test.ts, src/lobby/client.ts
Added the clone method to the first access of the response so when access again it dose not fail.
A fix for issue #1004.
=> LobbyClientError

scripts/changelog.js
Minor tweaks to the regex used to detect commit id & version bump commits
=> chore: improve changelog isVersionBump & commitID replacement regex

src/client/client.ts
- [ x ] Use a separate branch in your local repo (not `main`).
- [ x ] Test coverage is 100% (or you have a story for why it's ok).
Hi, i realised there is an issue with the type implementation. 
When passing a Game that has a diffrent ctx. It expects the default Ctx in the javascript client.
=> fix: Add `ctx` type parameter to client

docs/documentation/debugging.md, src/client/client.test.ts, src/client/client.ts, src/client/debug/Debug.svelte, src/client/debug/tests/debug.test.ts
Add more options to debug panel as per #1039
=> feat(debug): Add collapse on load & hide toggle button options

src/lobby/react.test.tsx, src/lobby/react.tsx
Fix for https://github.com/boardgameio/boardgame.io/issues/1043: pause polling for list of games when not showing list of games
(note: in end-to-end description. "Queries" refers to the polling queries against `/games` and `/games/<gamename>` endpoints)
- build and link against a game I am working on
-  Loaded localhost:8000, see "Choose a player name:", noted queries are not repeating
- Chose name and hit Enter, noted queries started
- Created game, `Join` game and hit `Play`, noted queries stopped
- `Exit match`, noted queries resumed
- `Play` game again, noted queries stopped
- `Exit lobby`, noted queries still stopped
- entered name and re-entered lobby, noted queries resume
- refresh browser, noted we go directly to game list and queries resume
- `Join` game and `Play` game, noted …
=> Lobby component: Stopped polling for list of games when list of games should not be visible

docs/documentation/debugging.md, docs/documentation/random.md
=> docs: add node/socket debugging information

src/server/api.test.ts, src/server/api.ts
Fixes https://github.com/boardgameio/boardgame.io/issues/1055. Prevents a user from creating a match with an invalid number of players (only applicable if `minPlayers` and/or `maxPlayers` are defined).
I tried to imitate the style and verbosity of the existing tests in `api.test.ts` with the tests I introduced, ~but technically some edge cases are not addressed by tests (eg. player count too low). If verbosity is preferred I'd be happy to add a few more test cases.~ but feel free to let me know if there's anywhere I can make improvements.
=> fix(lobby): block creation of matches with invalid player counts

package-lock.json, package.json
Very simple dependency update to suppress a deprecation warning. Turns out, we're not affected by this breaking change as far as I (and the tests) can tell! :rocket:
=> chore(deps): bump koa-body from 4.2.0 to 5.0.0

docs/documentation/tutorial.md
There is a missing `export` of `TicTacToeBoard` in `Board.js` in the React tutorial.
=> docs: Export TicTacToeBoard in Board.js

src/types.ts
I tried doing TicTacToe as much typed in TypeScript as possible. This `AiEnumerate` is the only type that I needed and that could be available from boardgame.io
----
Here is the code where I used the `AiEnumerate` type:
```TypeScript
type TicTacToeGameOver = {
draw?: boolean;
winner?: PlayerID;
}
type TicTacToeCell = PlayerID;
export type TicTacToeG = {
cells: TicTacToeCell[];
};
export type TicTacToeMoves = MoveMap<TicTacToeG> & {
clickCell: (G: TicTacToeG, ctx: Ctx, cellId: number) => void;
};
type TicTacToeGame = Game<TicTacToeG> & {
moves: TicTacToeMoves;
endIf: (G: TicTacToeG, ctx: Ctx) => TicTacToeGameOver | undefined;
};
export const TicTacToe: TicTacToeGame = {
...
ai: {
enumerate: (G, _ctx, _playerId) => {
const movesEnumeration: AiEnumerate = [];
const moves = TicTacToe.moves; …
```
=> TypeScript: AiEnumerate return type

docs/documentation/plugins.md
Minor addition to the plugin documentation, nodding at the existence of the `GameMethod` enum. Let me know if you want the example to be more substantial.
This PR addresses #1132.
=> docs: Add docs for plugin `GameMethod`
